name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run automated unit and integration tests
      run: dotnet test 
        /p:CollectCoverage=true 
        /p:CoverletOutput=TestResults/ 
        /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: SuDoKuHelper.Test/TestResults/coverage.info 
    - name: refresh coverage badge
      uses: fjogeleit/http-request-action@master
      with:
        url: https://camo.githubusercontent.com/13e44d4a506467f809b955b860e5d1cd53d4a09c0f4660afabece526ce6bfa63/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f4d7254616e58696e2f5375446f4b7548656c7065722f62616467652e7376673f6272616e63683d6d6173746572
        method: PURGE
